def get_spot_lists():
    url_spots_list = ["brouwersdam",
                      "ijsselmeer_mirns",
                      "wijk_aan_zee",
                      "ouddorp",
                      "veluwemeer",
                      "vrouwenpolder",
                      "cap-gris-nez",
                      "sunset_beach_table_view",
                      "tarifa-puerto",
                      "langebaan_za",
                      "wyk_foehr",
                      "skt_peter-ording",
                      "xanten",
                      "ambleteuse",
                      "guincho",
                      "cabedelo_de_viana",
                      "gafanha_da_nazare",
                      "dakhla_attitude"
                      ]
    spots_list = ["Brouwersdam",
                  "Mirns",
                  "Wijk",
                  "Ouddorp",
                  "Veluwemeer",
                  "Vrouwenpolder",
                  "Wissant",
                  "Sunset Beach",
                  "Tarifa",
                  "Langebaan",
                  "Wyk auf Föhr",
                  "Skt. Peter Ording",
                  "Xanten",
                  "Ambleteuse",
                  "Guincho",
                  "Viana do Castelo",
                  "Nazaré",
                  "Dakhla"
                  ]
    country_code_list = ["NL",
                         "NL",
                         "NL",
                         "NL",
                         "NL",
                         "NL",
                         "FR",
                         "ZA",
                         "ES",
                         "ZA",
                         "DE",
                         "DE",
                         "DE",
                         "FR",
                         "PT",
                         "PT",
                         "PT",
                         "MA"
                         ]
    print(str(len(country_code_list)) + " is the length of the country code")
    return [url_spots_list, spots_list, country_code_list]